package:
  name: constants
  version: "0.0.1"

source:
  path: ../my_package

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - constants

about:
  license: CC BY-NC-SA 4.0
  license_file: LICENSE.txt
